version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: pokemon-app
    restart: always
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 80:80

    networks:
      backend:
        aliases:
          - laravel-app

  db:
    image: mysql:latest
    container_name: pokemon-db
    restart: always
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - db

  db-admin:
    image: phpmyadmin:latest
    container_name: pokemon-admin-db
    restart: always
    depends_on:
      - db
    ports:
      - 3010:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=900M
    networks:
      backend:
        aliases:
          - db-admin  



networks:
  backend:
    name: backend-network
